version: "3.8"
services:
  app:
    image: brainstorm:latest
    build: ./
    volumes:
      - './:/home/app'
    ports:
      - 5000:5000
    environment:
      - REDIS_URL=${REDIS_URL}
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USE_TLS=${MAIL_USE_TLS}
      - MAIL_USE_SSL=${MAIL_USE_SSL}
    depends_on:
      - db
    tty: true

  worker:
    image: brainstorm:latest
    build: ./
    volumes:
      - './:/home/app'
    command: ["python", "worker.py"]
    environment:
      - REDIS_URL=${REDIS_URL}
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USE_TLS=${MAIL_USE_TLS}
      - MAIL_USE_SSL=${MAIL_USE_SSL}
    tty: True
    depends_on:
      - db

  scheduler:
    image: brainstorm:latest
    build: ./
    volumes:
      - './:/home/app'
    command: ["python", "scheduler.py", "-i", "15"]
    environment:
      - REDIS_URL=${REDIS_URL}
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
    tty: true
    depends_on:
      - db

  db:
    image: redis:alpine

  client:
    image: brainstorm-client:latest
    build: ./app/client
    ports:
      - 3000:3000
    stdin_open: true
    #depends_on:
    volumes:
      - './app/client/app:/home/app'
      - '/home/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=${REACT_APP_API_URL}
