version: "3.8"
services:
  app:
    image: brainstorm:latest
    build: ./
    volumes:
      - './app:/home/app'
    ports:
      - 5000:5000
    environment:
      - REDIS_URL=${REDIS_URL}
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
    depends_on:
      - db
    tty: true

  worker:
    image: brainstorm:latest
    build: ./
    volumes:
      - './app:/home/app'
    command: ["rq", "worker", "-u", "${REDIS_URL}", "high", "default", "low"]
    environment:
      - REDIS_URL=${REDIS_URL}
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
    tty: True
    depends_on:
      - db

  scheduler:
    image: brainstorm:latest
    build: ./
    volumes:
      - './app:/home/app'
    command: ["rqscheduler", "--host", "db", "--port", "6379"]
    environment:
      - REDIS_URL=${REDIS_URL}
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
    tty: true
    depends_on:
      - db

  db:
    image: redis:alpine

  
